### ISSUE TITLE
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by ndbroadbent** [zmxv/react-native-sound#152]
My app just crashed with the following error message:

<img width="487" alt="screenshot 2017-04-20 06 13 46" src="https://cloud.githubusercontent.com/assets/139536/25206201/a91fa980-2590-11e7-8008-4e125ad47dd9.png">

I was testing with a Debug build in the simulator. Versions:

* "react-native": "^0.43.3",
* "react-native-sound": "^0.9.1",
* Xcode 8.3.1
* iOS 10.3.1

If it's helpful, my app loads a lot of short sounds only once when it starts. I play and rewind those sounds repeatedly.

**Comment by ndbroadbent** [comment]
I managed to reproduce the crash after using the app for about one minute. This [issue on a different project](https://github.com/ivpusic/react-native-image-crop-picker/issues/235) suggests that it is probably a race condition. I'll submit a PR with a fix

**Comment by hiteshsahu** [comment]
I am having the same issue in Android

```

07-13 16:15:45.457 17280-17280/com.aproject E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.aproject, PID: 17280
                                                              java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
                                                                  at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
                                                                  at com.aproject.modules.BiometricModule.authenticationFailed(BiometricModule.java:280)
                                                                  at com.aproject.view.Fragments.FingerprintAuthenticationDialogFragment.onAuthenticationError(FingerprintAuthenticationDialogFragment.java:100)
                                                                  at com.aproject.view.Fragments.FingerprintUiHelper$4.run(FingerprintUiHelper.java:113)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5582)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hiteshsahu** [comment]
From Documentation

A native module is supposed to invoke its callback only once. It can, however, store the callback and invoke it later.

It is very important to highlight that the callback is not invoked immediately after the native function completes - remember that bridge communication is asynchronous, and this too is tied to the run loop.

**Comment by henninghall** [comment]
I also experience this issue. I suspect that the error might be related to the similar android issue #106. In that case it might be possible to solve it with a similar fix #202.

**Comment by gvenk** [comment]
@henninghall do you have more info about when this is happening, or logfiles?

**Comment by henninghall** [comment]
@gvenk Unfortunately, I have not been able to reproduce it, only seen it in error logs now and then. And I  have no detailed logs about how sounds are used.

@hiteshsahu do you know which version och react-native-sound you were using when you got your android errors? I suspect that v0.10.2 released 16 june might solve your issue.

**Comment by gvenk** [comment]
@henninghall ok, thanks. Maybe we have to reopen this issue to keep track of this problem.

**Comment by echo8795** [comment]
I have not been able to reproduce the issue but have seen in it on production. I think it can be solved by wrapping the callback.invoke in the 'onerror' of 'play' method in RNSoundModule

**Comment by rawrmaan** [comment]
@echo8795 That's a good idea. I'll do that on my own fork, test it in production, and report back when I have some data. I'm also going to move the `boolean callbackWasCalled = false;` one level up so it's shared by the completion and error callbacks.

**Comment by yaronlevi** [comment]
Any advances on the issue?
Having it on RN 0.51 and react-native-sound@0.10.4

**Comment by seankwalker** [comment]
can anyone confirm if #284 indeed fixed this?
