### ISSUE TITLE
Android:  player.prepare() catch error  and  the sound can be play but it will Part of loss in first 

### ISSUE THREAD

**Issue by JasonStu** [zmxv/react-native-sound#165]
@ReactMethod
  public void prepare(final String fileName, final Integer key, final Callback callback) {
    MediaPlayer player = null;

    player = playerPool.get(key);
    if (player != null /*&& player.isPlaying()*/) {
      player.stop();
      player.release();
      player = null;
      playerPool.remove(key);
    }

    player = createMediaPlayer(fileName);

    if (player == null) {
      WritableMap e = Arguments.createMap();
      e.putInt("code", -1);
      e.putString("message", "resource not found");
      callback.invoke(e);
      return;
    }
    try {
      player.prepare();
    } catch (Exception exception) {
              Log.e("RNSoundModule", "Exception", exception);

//**=====>I comment the code <=====**

//
//       WritableMap e = Arguments.createMap();
//        e.putInt("code", -1);
//        e.putString("message", exception.getMessage());
//        callback.invoke(e);
//        return;
    }
    this.playerPool.put(key, player);
    WritableMap props = Arguments.createMap();
    props.putDouble("duration", player.getDuration() * .001);
    callback.invoke(NULL, props);
  }

# the sound can be play but it will Part of loss in first 

```

E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
D/MediaPlayer: setSubtitleAnchor in MediaPlayer
E/MediaPlayer: prepareAsync called in state 8, mPlayer(0xc50a3820)
E/RNSoundModule: Exception
                 java.lang.IllegalStateException
                     at android.media.MediaPlayer._prepare(Native Method)
                     at android.media.MediaPlayer.prepare(MediaPlayer.java:1204)
                     at com.zmxv.RNSound.RNSoundModule.prepare(RNSoundModule.java:59)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                     at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                     at android.os.Handler.handleCallback(Handler.java:751)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                     at android.os.Looper.loop(Looper.java:154)
                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                     at java.lang.Thread.run(Thread.java:761)
```

**Comment by henrikra** [comment]
@JasonStu Is this fixed?

**Comment by pengyanb** [comment]
Same issue

**Comment by pengyanb** [comment]
Fixed by [fix prepareAsync called in state 8, mPlayer(0xd38e8800)](https://github.com/zmxv/react-native-sound/pull/147/commits/e4c987dc1204c03deec9c268771b09881923ccb7)

**Comment by Qadomy** [comment]
did you find the problem?
