### ISSUE TITLE
RNSound.setSpeed

### ISSUE THREAD

**Issue by micahrye** [zmxv/react-native-sound#193]
Getting error using "setSpeed" from javascript on release version running on android device. Not seeing error when running on emulator in development. 

Android
react-native 0.44.0

Error: 
```
I/ReactNativeJS( 2980): GETTING = null
E/MediaPlayer( 2980): Should have subtitle controller already set
W/dalvikvm( 2980): threadid=13: thread exiting with uncaught exception (group=0x4156eba8)
E/AndroidRuntime( 2980): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 2980): Process: com.cogplay, PID: 2980
E/AndroidRuntime( 2980): java.lang.RuntimeException: Could not invoke RNSound.setSpeed
E/AndroidRuntime( 2980): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:382)
E/AndroidRuntime( 2980): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
E/AndroidRuntime( 2980): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime( 2980): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2980): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2980): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime( 2980): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2980): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
E/AndroidRuntime( 2980): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime( 2980): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 2980): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2980): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2980): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
E/AndroidRuntime( 2980): 	... 8 more
E/AndroidRuntime( 2980): Caused by: java.lang.NoSuchMethodError: android.media.MediaPlayer.getPlaybackParams
E/AndroidRuntime( 2980): 	at com.zmxv.RNSound.RNSoundModule.setSpeed(RNSoundModule.java:161)
E/AndroidRuntime( 2980): 	... 11 more
```

**Comment by rneiss** [comment]
cc: @twitwi  @benvium

**Comment by ohtangza** [comment]
Any updates?

**Comment by lukecwilliams** [comment]
Android "speed" is listed as both working and not working.  Should this work?

Available in both from the table:
![image](https://user-images.githubusercontent.com/19214773/28938099-005bca18-785b-11e7-8816-75a38c044777.png)

But the description says iOS only:
![image](https://user-images.githubusercontent.com/19214773/28938119-0f28f804-785b-11e7-9c25-6f9fda171d37.png)

**Comment by gvenk** [comment]
Which version of Android are you using? The `android.media.MediaPlayer.getPlaybackParams()` method is available since Android 6.0 ([API Level 23](https://developer.android.com/reference/android/media/MediaPlayer.html#setPlaybackParams(android.media.PlaybackParams))), so it could have something to do with this.

**Comment by trepidity** [comment]
@lukecwilliams I created a new issue for your question. #257

**Comment by lukecwilliams** [comment]
@trepidity thanks!

**Comment by esutton** [comment]
+1 Release build on Android 

**RNSoundModule.java line 215
com.zmxv.RNSound.RNSoundModule.setSpeed**

````
		"react": "^16.2.0",
		"react-native": "^0.53.3",
		"react-native-sound": "v0.10.2",
````

### Crashlytics

![screen shot 2018-03-09 at 9 53 12 am](https://user-images.githubusercontent.com/6115047/37216173-c51f37d4-237f-11e8-9b4b-0087103b1e52.png)

**Comment by ohtangza** [comment]
@ghsdh3409 Are you experiencing this issue...?

**Comment by ghsdh3409** [comment]
@esutton Android setSpeed works in the API level >= 23.

**Comment by esutton** [comment]
@ghsdh3409 Thank you!  My mistake.  

Not sure why it threw an exception since it looked like it should have returned on an API 19 device rather than throwing?
````
  @ReactMethod
  public void setSpeed(final Double key, final Float speed) {
	if (android.os.Build.VERSION.SDK_INT < 23) {
	  Log.w("RNSoundModule", "setSpeed ignored due to sdk limit");
	  return;
	}

    MediaPlayer player = this.playerPool.get(key);
    if (player != null) {
      player.setPlaybackParams(player.getPlaybackParams().setSpeed(speed));
    }
  }
````

https://github.com/zmxv/react-native-sound/blob/253a35ca6841b8087081ec2d3565cbd2f3ea9612/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java#L355

**Comment by trepidity** [comment]
Now that I look at this code, I wish it had been written without the “return”. Would anyone want to write a PR and write it without the return?

**Comment by saurabhkanswal** [comment]
@esutton any update on this issue, we are also facing this issue on android version greater than 4, like android 10,6 and 9.
