### ISSUE TITLE
Unable to load mp3 on iOS

### ISSUE THREAD

**Issue by voidvoxel** [zmxv/react-native-sound#22]
```
transforming [======================================= ] 99% 539/546TypeError: unsupported file type
    at lookup (/Users/user/Dev/app/app/node_modules/image-size/lib/index.js:35:9)
    at /Users/user/Dev/app/app/node_modules/image-size/lib/index.js:93:22
    at /Users/user/Dev/app/app/node_modules/image-size/lib/index.js:50:9
    at /Users/user/Dev/app/app/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```
It works fine if I put my mp3 file outside the project scope (on my Desktop for instance) and I just load by '/Users/user/Desktop/abc.mp3', but when I move the mp3 file into my project, it throws this error 0_o

**Comment by voidvoxel** [comment]
[fixed](https://github.com/facebook/react-native/issues/6527)
