### ISSUE TITLE
Playing sound the second time completes but crashes the app with NullPointerException

### ISSUE THREAD

**Issue by Progoogler** [zmxv/react-native-sound#372]
```
E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.link, PID: 15253
        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
            at com.zmxv.RNSound.RNSoundModule.onAudioFocusChange(RNSoundModule.java:391)
            at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:3238)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6897)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

```
      this.cashSound.play((success) => {
        if (success) {
          console.log('successfully finished playing');

          // For Example: If I do this:
          this.cashSound.play();
          // The app will crash with the above error.

        } else {
          console.log('playback failed due to audio decoding errors');
          this.cashSound.reset();
        }
      });
```

The error above occurs immediately after the second sound finishes playing. I've tried resetting the instance after successfully playing with `this.cashSound.reset()`, `this.cashSound.release()`, and resetting the sound with a new `this.cashSound = new Sound(...);` within the `success` condition but to no avail. 
Is there something that I am missing? Please let me know if you have any idea about what could be causing this issue.

**Comment by Progoogler** [comment]
Strange enough it started working again on its own. I do not have a clue as to why this happened. Best of luck to whoever comes by this issue after me, only time will tell!
