### ISSUE TITLE
Boolean Exception 

### ISSUE THREAD

**Issue by Baraa-bi** [zmxv/react-native-sound#410]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.zmxv.RNSound.RNSoundModule.onAudioFocusChange(RNSoundModule.java:391)
       at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:3131)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by paulmelnikow** [comment]
Hi! Are you still having this issue? Which version of the library is it?
