### ISSUE TITLE
IllegalStateException Crash

### ISSUE THREAD

**Issue by UberMC** [zmxv/react-native-sound#479]
```
java.lang.IllegalStateException
at android.media.MediaPlayer.isPlaying(Native Method)
at com.zmxv.RNSound.RNSoundModule.onAudioFocusChange(RNSoundModule.java:413)
at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2950)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
```

7.0 Galaxy S6 edge  SM-G925F

**Comment by uysalut** [comment]
I have exact same error reported from bugsnag. Any ideas?

**Comment by fluiddot** [comment]
I’m also getting this crash daily in the crash reports but I haven’t found out yet what’s causing it. Is anyone else having it? Any ideas?

**Comment by paulmelnikow** [comment]
Hi! If you're still experiencing this issue, could you please open an issue with more details following the issue template? Thanks!
